version: 2

models:
  - name: dim_station
    columns:
      - name: station_id
        tests:
          - unique
          - not_null
      - name: name
        tests:
          - not_null
      - name: location
        tests:
          - not_null